### PR TITLE
Linking logo to home page.

### PR DESCRIPTION
**Pull request by tdickers**
Is linking the logo intuitive enough, or do we want a button saying "home"?

Preview it at: https://deploy-preview-4--igenottawa.netlify.com/

### CODE REVIEW

**Comment by TamimiGitHub** [comment]
I would go for adding a `home` link on the top right please

**Comment by tdickers** [comment]
Will do Friday evening.

**Comment by TamimiGitHub** [comment]
For demo purposes, can you please 
1. Link to `https://igenottawaca.previews.rebel.com` instead
2. Add the href for the igen logo in then [list](https://igenottawa.netlify.com/list) page as well

**Comment by tdickers** [comment]
Removed the logo links and added a button.

Hey @TamimiGitHub, I added the inter-page links ("Post an Event" and "Events List") here as well since it was helpful in coming up with a layout that was consistent and would scale well with mobile, and helped me to see how to make the Home and inter-page links work well together. Floating the button in the upper right had some drawbacks re: a responsive layout (tried 2 different approaches), so I went with a simpler stacked layout. (I'm sure it's possible.)

This overlaps with https://github.com/igenday/rhok-igenottawa/pull/7; I'd propose combining the two, maybe using the Bootstrap button styling with the Pure CSS grid layout? (If so, we'd want to add Bootstrap CSS to create.html.) Alternatively Pure CSS has very similar button styles: https://purecss.io/buttons/#customizing-buttons

Screen Shot 2019-05-04 at 12 40 38 AM
Screen Shot 2019-05-04 at 12 40 27 AM

**Comment by TamimiGitHub** [comment]
This indeed overlaps with #7, I'll go ahead and close it as I like this approach more! And using pure over bootstrap suffice. Thanks Tai, 🚢 it!

Cann you please also move the cards from the project once this PR is merged

**Pull request merged**
